### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by saquibntt** [zeyiwen/thundersvm#81]
Hi,

I tried to use thunderSVM in place of normal SVM. I changed my labels using sklearn.preprocessor.LabelEncoder()  to integers. Below is the  stacktrace:

`Traceback (most recent call last):
  File "svm_gmm_logreg.py", line 211, in <module>
    SVMMethod()
  File "svm_gmm_logreg.py", line 155, in SVMMethod
    clf.fit(xTrainScaled, yTrain)
  File "/home/nvidia/Documents/folder1/speech_emotion_recognition/svm_gmm_logreg/thundersvmScikit.py", line 72, in fit
    y = self.label_validate(y)
  File "/home/nvidia/Documents/folder1/speech_emotion_recognition/svm_gmm_logreg/thundersvmScikit.py", line 63, in label_validate
    return column_or_1d(y, warn=True).astype(np.float64)
ValueError: could not convert string to float: anger
`

I am using Ubuntu 16, on Tegra processor with cuda 9.

**Comment by GODqinbin** [comment]
It seems the label you input is still string type. So I guess you didn't successfully change your label type to integers. Can you tell me the specific instructions of LabelEncoder() you used?

**Comment by zeyiwen** [comment]
This issue should be solved now.
